# Example local secrets file for testing. DO NOT commit real keys to Git.
# Save this file as .streamlit/secrets.toml for local testing only.
OPENAI_API_KEY = "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"
